export { default as Header } from './header/Header'
export { default as NavMenu } from './nav-menu/NavMenu'
export { default as Content } from './content/Content'
export { default as MovieDetail } from './movie-detail/MovieDetail'
export { default as Movie } from './movie-list/Movie'
export { default as MovieList } from './movie-list/MovieList'
